image: gitpod/workspace-full
tasks:
  - name: Install dependencies
    init: |
      yarn --check-files --silent

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: true
    addBadge: false
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - christian-kohler.path-intellisense
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - ecmel.vscode-html-css
    - editorconfig.editorconfig
    - ms-vscode.vscode-typescript-next
    - visualstudioexptteam.vscodeintellicode
    - xabikos.javascriptsnippets
    - zignd.html-css-class-completion
    - aaron-bond.better-comments
