name: Build

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/fermium', 'lts/gallium', current]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.8.29
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Build
        run: yarn build
