name: Test

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.18.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.7.11
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Test
        run: yarn test:ci
